# Site
name: "Interactive Pan-Genome Library"
title: "Interactive Pan-Genome Library"
description: "Collection of interactive pan-genomes featuring collections of microbes."
logo: 'assets/images/gig-map-logos_black.png'
favicon: 'assets/images/gig-map-logos_black.png'
baseurl: 
google_analytics: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sam:
    name: Sam Minot
    display_name: Sam Minot
    gravatar: 
    email: sminot@fredhutch.org
    web: https://minot.bio
    twitter: https://twitter.com/sminot
    description: "Microbiome scientist"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
